# Generated by Django 5.2.1 on 2025-05-14 10:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("skillmatch", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="candidate",
            name="status",
            field=models.CharField(
                choices=[("active", "Active"), ("inactive", "Inactive")],
                default="active",
                help_text="Whether this record is active or inactive",
                max_length=10,
            ),
        ),
        migrations.AddField(
            model_name="job",
            name="status",
            field=models.CharField(
                choices=[("active", "Active"), ("inactive", "Inactive")],
                default="active",
                help_text="Whether this record is active or inactive",
                max_length=10,
            ),
        ),
    ]
